### ISSUE TITLE
Idle Until Urgent follow up suggestion

### ISSUE THREAD

**Issue by munizart** [nikcorg/tldr#1]
Hi there @nikcorg, I saw you put Philip Walton's `Idle Until Urgent` in your list and if you don't mind I'd like to suggest you a article I wrote that I think you may find interesting too.
https://munizart.github.io/2018/10/11/introducing-idle-comp/
It's about a package I published based on Walton's Idle Until Urgent philosophy.

Best regards,
Artur Muniz

**Comment by nikcorg** [comment]
Cool, thanks very much. I'll put it on my reading list :-)
